### ISSUE TITLE
Extend validation to ensure actual files referred in nav.json exist in `docs` directory

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/nav-json-validator#2]
A few times now, things like this happen - https://github.com/dequelabs/attest-java/pull/146/files#r364852017

And it is hard to catch these in review esp., with giant PR's of documentation changes.

**Comment by stephenmathieson** [comment]
Looks like this bit us again: https://github.com/dequelabs/attest-node-suite/pull/424

I'll throw something together real quick
